server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xu5219
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
cookie:
  path: ./config/jdcookie.txt