server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8
logging:
  config: config/logback.xml
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
cookie:
  path: ./config/jdcookie.txt